// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_vpgXJD6z-lquKV4dBpjPIfX0eZyteLM',
    appId: '1:225529638875:android:e2ee52afbb0c8ed0a341fe',
    messagingSenderId: '225529638875',
    projectId: 'western-oarlock-466702-d3',
    storageBucket: 'western-oarlock-466702-d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBenqS8B2XVcUe6n5-0Vrv1xehuFmMi5gI',
    appId: '1:225529638875:ios:94ea7c5d16ab97c7a341fe',
    messagingSenderId: '225529638875',
    projectId: 'western-oarlock-466702-d3',
    storageBucket: 'western-oarlock-466702-d3.firebasestorage.app',
    androidClientId: '225529638875-fq2c9grbmm8vsdlmcdiakqq6657tb39d.apps.googleusercontent.com',
    iosClientId: '225529638875-loisn3qs9bk5dho295p3fvhtq30ttpc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.sneakPeak',
  );

}